version: "2"

linters:
  default: standard
  enable:
    - gosec
    - gocritic
    - gocyclo
    - unconvert
    - misspell
    - modernize
    - testifylint

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/germanamz/shelly

linters-settings:
  gocyclo:
    min-complexity: 15
